
title: fiksi
baseurl: "/fiksi"
url: "https://fxah.github.io"
timezone: Asia/Jakarta
twitter_username: fxah
github_username:  fxah
permalink: /:year/:month/:day/:title/
paginate: 8
markdown: kramdown
kramdown:
    input: GFM
gems:
    - jemoji
exclude: 
    - prepare-label.sh
    - Gemfile
    - Gemfile.lock
